// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prime/prime_server/primepb/prime.proto

package primepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Prime struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prime) Reset()         { *m = Prime{} }
func (m *Prime) String() string { return proto.CompactTextString(m) }
func (*Prime) ProtoMessage()    {}
func (*Prime) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f4c8c8583142cfc, []int{0}
}

func (m *Prime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prime.Unmarshal(m, b)
}
func (m *Prime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prime.Marshal(b, m, deterministic)
}
func (m *Prime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prime.Merge(m, src)
}
func (m *Prime) XXX_Size() int {
	return xxx_messageInfo_Prime.Size(m)
}
func (m *Prime) XXX_DiscardUnknown() {
	xxx_messageInfo_Prime.DiscardUnknown(m)
}

var xxx_messageInfo_Prime proto.InternalMessageInfo

func (m *Prime) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PrimeManyTimesRequest struct {
	Prime                *Prime   `protobuf:"bytes,1,opt,name=prime,proto3" json:"prime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeManyTimesRequest) Reset()         { *m = PrimeManyTimesRequest{} }
func (m *PrimeManyTimesRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeManyTimesRequest) ProtoMessage()    {}
func (*PrimeManyTimesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f4c8c8583142cfc, []int{1}
}

func (m *PrimeManyTimesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeManyTimesRequest.Unmarshal(m, b)
}
func (m *PrimeManyTimesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeManyTimesRequest.Marshal(b, m, deterministic)
}
func (m *PrimeManyTimesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeManyTimesRequest.Merge(m, src)
}
func (m *PrimeManyTimesRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeManyTimesRequest.Size(m)
}
func (m *PrimeManyTimesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeManyTimesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeManyTimesRequest proto.InternalMessageInfo

func (m *PrimeManyTimesRequest) GetPrime() *Prime {
	if m != nil {
		return m.Prime
	}
	return nil
}

type PrimeManyTimesResponse struct {
	PrimeFactor          int32    `protobuf:"varint,1,opt,name=prime_factor,json=primeFactor,proto3" json:"prime_factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeManyTimesResponse) Reset()         { *m = PrimeManyTimesResponse{} }
func (m *PrimeManyTimesResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeManyTimesResponse) ProtoMessage()    {}
func (*PrimeManyTimesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f4c8c8583142cfc, []int{2}
}

func (m *PrimeManyTimesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeManyTimesResponse.Unmarshal(m, b)
}
func (m *PrimeManyTimesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeManyTimesResponse.Marshal(b, m, deterministic)
}
func (m *PrimeManyTimesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeManyTimesResponse.Merge(m, src)
}
func (m *PrimeManyTimesResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeManyTimesResponse.Size(m)
}
func (m *PrimeManyTimesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeManyTimesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeManyTimesResponse proto.InternalMessageInfo

func (m *PrimeManyTimesResponse) GetPrimeFactor() int32 {
	if m != nil {
		return m.PrimeFactor
	}
	return 0
}

func init() {
	proto.RegisterType((*Prime)(nil), "prime.Prime")
	proto.RegisterType((*PrimeManyTimesRequest)(nil), "prime.PrimeManyTimesRequest")
	proto.RegisterType((*PrimeManyTimesResponse)(nil), "prime.PrimeManyTimesResponse")
}

func init() {
	proto.RegisterFile("prime/prime_server/primepb/prime.proto", fileDescriptor_9f4c8c8583142cfc)
}

var fileDescriptor_9f4c8c8583142cfc = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2b, 0x28, 0xca, 0xcc,
	0x4d, 0xd5, 0x07, 0x93, 0xf1, 0xc5, 0xa9, 0x45, 0x65, 0xa9, 0x45, 0x10, 0x4e, 0x41, 0x12, 0x84,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xe4, 0xb9, 0x58, 0x03, 0x40,
	0x0c, 0x21, 0x31, 0x2e, 0xb6, 0xbc, 0xd2, 0xdc, 0xa4, 0xd4, 0x22, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xd6, 0x20, 0x28, 0x4f, 0xc9, 0x9a, 0x4b, 0x14, 0xac, 0xc0, 0x37, 0x31, 0xaf, 0x32, 0x24, 0x33,
	0x37, 0xb5, 0x38, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x89, 0x0b, 0x62, 0x04, 0x58,
	0x3d, 0xb7, 0x11, 0x8f, 0x1e, 0xc4, 0x74, 0xb0, 0xe2, 0x20, 0xa8, 0xe9, 0xd6, 0x5c, 0x62, 0xe8,
	0x9a, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x14, 0xb9, 0x78, 0x20, 0x4e, 0x4c, 0x4b, 0x4c,
	0x2e, 0xc9, 0x87, 0x59, 0xca, 0x0d, 0x16, 0x73, 0x03, 0x0b, 0x19, 0x25, 0x72, 0xf1, 0x80, 0x35,
	0x07, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0x05, 0x72, 0xf1, 0xa1, 0x1a, 0x26, 0x24, 0x83,
	0x6c, 0x27, 0xba, 0x03, 0xa5, 0x64, 0x71, 0xc8, 0x42, 0x5c, 0xa0, 0xc4, 0x60, 0xc0, 0xe8, 0xc4,
	0x19, 0xc5, 0x0e, 0x0d, 0x9b, 0x24, 0x36, 0x70, 0xb0, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xcd, 0xd8, 0x05, 0x2e, 0x40, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrimeServiceClient is the client API for PrimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeServiceClient interface {
	// server Streaming
	PrimeManyTimes(ctx context.Context, in *PrimeManyTimesRequest, opts ...grpc.CallOption) (PrimeService_PrimeManyTimesClient, error)
}

type primeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeServiceClient(cc grpc.ClientConnInterface) PrimeServiceClient {
	return &primeServiceClient{cc}
}

func (c *primeServiceClient) PrimeManyTimes(ctx context.Context, in *PrimeManyTimesRequest, opts ...grpc.CallOption) (PrimeService_PrimeManyTimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrimeService_serviceDesc.Streams[0], "/prime.PrimeService/PrimeManyTimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &primeServicePrimeManyTimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrimeService_PrimeManyTimesClient interface {
	Recv() (*PrimeManyTimesResponse, error)
	grpc.ClientStream
}

type primeServicePrimeManyTimesClient struct {
	grpc.ClientStream
}

func (x *primeServicePrimeManyTimesClient) Recv() (*PrimeManyTimesResponse, error) {
	m := new(PrimeManyTimesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrimeServiceServer is the server API for PrimeService service.
type PrimeServiceServer interface {
	// server Streaming
	PrimeManyTimes(*PrimeManyTimesRequest, PrimeService_PrimeManyTimesServer) error
}

// UnimplementedPrimeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrimeServiceServer struct {
}

func (*UnimplementedPrimeServiceServer) PrimeManyTimes(req *PrimeManyTimesRequest, srv PrimeService_PrimeManyTimesServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeManyTimes not implemented")
}

func RegisterPrimeServiceServer(s *grpc.Server, srv PrimeServiceServer) {
	s.RegisterService(&_PrimeService_serviceDesc, srv)
}

func _PrimeService_PrimeManyTimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeManyTimesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeServiceServer).PrimeManyTimes(m, &primeServicePrimeManyTimesServer{stream})
}

type PrimeService_PrimeManyTimesServer interface {
	Send(*PrimeManyTimesResponse) error
	grpc.ServerStream
}

type primeServicePrimeManyTimesServer struct {
	grpc.ServerStream
}

func (x *primeServicePrimeManyTimesServer) Send(m *PrimeManyTimesResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PrimeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prime.PrimeService",
	HandlerType: (*PrimeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeManyTimes",
			Handler:       _PrimeService_PrimeManyTimes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "prime/prime_server/primepb/prime.proto",
}
