// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calc_server/calcpb/calc.proto

package calcpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Opperands struct {
	Num1                 int64    `protobuf:"varint,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2                 int64    `protobuf:"varint,2,opt,name=num2,proto3" json:"num2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Opperands) Reset()         { *m = Opperands{} }
func (m *Opperands) String() string { return proto.CompactTextString(m) }
func (*Opperands) ProtoMessage()    {}
func (*Opperands) Descriptor() ([]byte, []int) {
	return fileDescriptor_df39afad19512503, []int{0}
}

func (m *Opperands) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Opperands.Unmarshal(m, b)
}
func (m *Opperands) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Opperands.Marshal(b, m, deterministic)
}
func (m *Opperands) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Opperands.Merge(m, src)
}
func (m *Opperands) XXX_Size() int {
	return xxx_messageInfo_Opperands.Size(m)
}
func (m *Opperands) XXX_DiscardUnknown() {
	xxx_messageInfo_Opperands.DiscardUnknown(m)
}

var xxx_messageInfo_Opperands proto.InternalMessageInfo

func (m *Opperands) GetNum1() int64 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *Opperands) GetNum2() int64 {
	if m != nil {
		return m.Num2
	}
	return 0
}

type SumRequest struct {
	Opperands            *Opperands `protobuf:"bytes,1,opt,name=opperands,proto3" json:"opperands,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df39afad19512503, []int{1}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetOpperands() *Opperands {
	if m != nil {
		return m.Opperands
	}
	return nil
}

type SumResponse struct {
	Sum                  int64    `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df39afad19512503, []int{2}
}

func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (m *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(m, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetSum() int64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func init() {
	proto.RegisterType((*Opperands)(nil), "calulator.Opperands")
	proto.RegisterType((*SumRequest)(nil), "calulator.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "calulator.SumResponse")
}

func init() {
	proto.RegisterFile("calculator/calc_server/calcpb/calc.proto", fileDescriptor_df39afad19512503)
}

var fileDescriptor_df39afad19512503 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x48, 0x4e, 0xcc, 0x49,
	0x2e, 0xcd, 0x49, 0x2c, 0xc9, 0x2f, 0xd2, 0x07, 0x31, 0xe3, 0x8b, 0x53, 0x8b, 0xca, 0x52, 0x21,
	0xec, 0x82, 0x24, 0x30, 0xa5, 0x57, 0x50, 0x94, 0x5f, 0x92, 0x2f, 0xc4, 0x99, 0x9c, 0x98, 0x03,
	0x51, 0xa8, 0x64, 0xcc, 0xc5, 0xe9, 0x5f, 0x50, 0x90, 0x5a, 0x94, 0x98, 0x97, 0x52, 0x2c, 0x24,
	0xc4, 0xc5, 0x92, 0x57, 0x9a, 0x6b, 0x28, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1c, 0x04, 0x66, 0x43,
	0xc5, 0x8c, 0x24, 0x98, 0xe0, 0x62, 0x46, 0x4a, 0x0e, 0x5c, 0x5c, 0xc1, 0xa5, 0xb9, 0x41, 0xa9,
	0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x46, 0x5c, 0x9c, 0xf9, 0x30, 0x23, 0xc0, 0x5a, 0xb9, 0x8d,
	0x44, 0xf4, 0xe0, 0x36, 0xe8, 0xc1, 0x8d, 0x0f, 0x42, 0x28, 0x53, 0x92, 0xe7, 0xe2, 0x06, 0x9b,
	0x50, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc0, 0xc5, 0x5c, 0x5c, 0x9a, 0x0b, 0xb5, 0x17,
	0xc4, 0x34, 0x72, 0x01, 0x5b, 0x11, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0x64, 0xc6, 0xc5,
	0x1c, 0x5c, 0x9a, 0x2b, 0x24, 0x8a, 0x64, 0x2c, 0xc2, 0x01, 0x52, 0x62, 0xe8, 0xc2, 0x10, 0x53,
	0x95, 0x18, 0x9c, 0x38, 0xa2, 0xd8, 0x20, 0xbe, 0x4f, 0x62, 0x03, 0xfb, 0xdc, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xa4, 0x27, 0x3a, 0xa1, 0x25, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SumServiceClient is the client API for SumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SumServiceClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
}

type sumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSumServiceClient(cc grpc.ClientConnInterface) SumServiceClient {
	return &sumServiceClient{cc}
}

func (c *sumServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calulator.SumService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SumServiceServer is the server API for SumService service.
type SumServiceServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
}

// UnimplementedSumServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSumServiceServer struct {
}

func (*UnimplementedSumServiceServer) Sum(ctx context.Context, req *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}

func RegisterSumServiceServer(s *grpc.Server, srv SumServiceServer) {
	s.RegisterService(&_SumService_serviceDesc, srv)
}

func _SumService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SumServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calulator.SumService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SumServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SumService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calulator.SumService",
	HandlerType: (*SumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _SumService_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calculator/calc_server/calcpb/calc.proto",
}
