// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calc_server/calcpb/calc.proto

package calcpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Opperands struct {
	Num1                 int64    `protobuf:"varint,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2                 int64    `protobuf:"varint,2,opt,name=num2,proto3" json:"num2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Opperands) Reset()         { *m = Opperands{} }
func (m *Opperands) String() string { return proto.CompactTextString(m) }
func (*Opperands) ProtoMessage()    {}
func (*Opperands) Descriptor() ([]byte, []int) {
	return fileDescriptor_df39afad19512503, []int{0}
}

func (m *Opperands) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Opperands.Unmarshal(m, b)
}
func (m *Opperands) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Opperands.Marshal(b, m, deterministic)
}
func (m *Opperands) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Opperands.Merge(m, src)
}
func (m *Opperands) XXX_Size() int {
	return xxx_messageInfo_Opperands.Size(m)
}
func (m *Opperands) XXX_DiscardUnknown() {
	xxx_messageInfo_Opperands.DiscardUnknown(m)
}

var xxx_messageInfo_Opperands proto.InternalMessageInfo

func (m *Opperands) GetNum1() int64 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *Opperands) GetNum2() int64 {
	if m != nil {
		return m.Num2
	}
	return 0
}

type Opperator struct {
	Opperator            string   `protobuf:"bytes,1,opt,name=opperator,proto3" json:"opperator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Opperator) Reset()         { *m = Opperator{} }
func (m *Opperator) String() string { return proto.CompactTextString(m) }
func (*Opperator) ProtoMessage()    {}
func (*Opperator) Descriptor() ([]byte, []int) {
	return fileDescriptor_df39afad19512503, []int{1}
}

func (m *Opperator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Opperator.Unmarshal(m, b)
}
func (m *Opperator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Opperator.Marshal(b, m, deterministic)
}
func (m *Opperator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Opperator.Merge(m, src)
}
func (m *Opperator) XXX_Size() int {
	return xxx_messageInfo_Opperator.Size(m)
}
func (m *Opperator) XXX_DiscardUnknown() {
	xxx_messageInfo_Opperator.DiscardUnknown(m)
}

var xxx_messageInfo_Opperator proto.InternalMessageInfo

func (m *Opperator) GetOpperator() string {
	if m != nil {
		return m.Opperator
	}
	return ""
}

type SumRequest struct {
	Opperands            *Opperands `protobuf:"bytes,1,opt,name=opperands,proto3" json:"opperands,omitempty"`
	Opperator            *Opperator `protobuf:"bytes,2,opt,name=opperator,proto3" json:"opperator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df39afad19512503, []int{2}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetOpperands() *Opperands {
	if m != nil {
		return m.Opperands
	}
	return nil
}

func (m *SumRequest) GetOpperator() *Opperator {
	if m != nil {
		return m.Opperator
	}
	return nil
}

type SumResponse struct {
	Sum                  float64  `protobuf:"fixed64,1,opt,name=sum,proto3" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df39afad19512503, []int{3}
}

func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (m *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(m, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetSum() float64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

type SquareRootRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SquareRootRequest) Reset()         { *m = SquareRootRequest{} }
func (m *SquareRootRequest) String() string { return proto.CompactTextString(m) }
func (*SquareRootRequest) ProtoMessage()    {}
func (*SquareRootRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df39afad19512503, []int{4}
}

func (m *SquareRootRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SquareRootRequest.Unmarshal(m, b)
}
func (m *SquareRootRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SquareRootRequest.Marshal(b, m, deterministic)
}
func (m *SquareRootRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SquareRootRequest.Merge(m, src)
}
func (m *SquareRootRequest) XXX_Size() int {
	return xxx_messageInfo_SquareRootRequest.Size(m)
}
func (m *SquareRootRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SquareRootRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SquareRootRequest proto.InternalMessageInfo

func (m *SquareRootRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type SquareRootReponse struct {
	NumberRoot           float64  `protobuf:"fixed64,1,opt,name=number_root,json=numberRoot,proto3" json:"number_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SquareRootReponse) Reset()         { *m = SquareRootReponse{} }
func (m *SquareRootReponse) String() string { return proto.CompactTextString(m) }
func (*SquareRootReponse) ProtoMessage()    {}
func (*SquareRootReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df39afad19512503, []int{5}
}

func (m *SquareRootReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SquareRootReponse.Unmarshal(m, b)
}
func (m *SquareRootReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SquareRootReponse.Marshal(b, m, deterministic)
}
func (m *SquareRootReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SquareRootReponse.Merge(m, src)
}
func (m *SquareRootReponse) XXX_Size() int {
	return xxx_messageInfo_SquareRootReponse.Size(m)
}
func (m *SquareRootReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SquareRootReponse.DiscardUnknown(m)
}

var xxx_messageInfo_SquareRootReponse proto.InternalMessageInfo

func (m *SquareRootReponse) GetNumberRoot() float64 {
	if m != nil {
		return m.NumberRoot
	}
	return 0
}

func init() {
	proto.RegisterType((*Opperands)(nil), "calulator.Opperands")
	proto.RegisterType((*Opperator)(nil), "calulator.Opperator")
	proto.RegisterType((*SumRequest)(nil), "calulator.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "calulator.SumResponse")
	proto.RegisterType((*SquareRootRequest)(nil), "calulator.SquareRootRequest")
	proto.RegisterType((*SquareRootReponse)(nil), "calulator.SquareRootReponse")
}

func init() {
	proto.RegisterFile("calculator/calc_server/calcpb/calc.proto", fileDescriptor_df39afad19512503)
}

var fileDescriptor_df39afad19512503 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0x7e, 0xd3, 0xbe, 0x06, 0x33, 0xb9, 0xd8, 0x45, 0xa4, 0x48, 0xa1, 0xb2, 0xa7, 0x8a, 0x10,
	0x31, 0xf5, 0x17, 0xe8, 0xcd, 0x8b, 0xb0, 0xb9, 0x79, 0x09, 0x49, 0x3a, 0x07, 0x21, 0xd9, 0xd9,
	0xee, 0x47, 0x7f, 0xbf, 0x64, 0x37, 0x1f, 0x15, 0xe9, 0x69, 0x67, 0x9f, 0x7d, 0xbe, 0x96, 0x81,
	0x5d, 0x53, 0xb5, 0x8d, 0x6b, 0x2b, 0x4b, 0xfa, 0xb9, 0x1f, 0x4b, 0x83, 0xfa, 0x84, 0x61, 0x56,
	0xb5, 0x3f, 0x32, 0xa5, 0xc9, 0x12, 0x4b, 0x9a, 0xaa, 0x0d, 0x44, 0xbe, 0x87, 0xe4, 0x53, 0x29,
	0xd4, 0x95, 0x3c, 0x18, 0xc6, 0xe0, 0xbf, 0x74, 0xdd, 0xcb, 0x3a, 0x7a, 0x88, 0x76, 0x4b, 0xe1,
	0xe7, 0x01, 0xcb, 0xd7, 0x8b, 0x09, 0xcb, 0xf9, 0xe3, 0x28, 0xb2, 0xa4, 0xd9, 0x06, 0x12, 0x1a,
	0x2f, 0x5e, 0x99, 0x88, 0x19, 0xe0, 0x16, 0xa0, 0x70, 0x9d, 0xc0, 0xa3, 0x43, 0x63, 0x59, 0x3e,
	0x72, 0xe5, 0xc1, 0x78, 0x6e, 0x9a, 0xdf, 0x66, 0x53, 0x99, 0x6c, 0x6a, 0x22, 0x66, 0xda, 0xac,
	0xe9, 0xfd, 0x17, 0x17, 0x34, 0x96, 0xf4, 0x79, 0xea, 0x16, 0x52, 0x9f, 0x6a, 0x14, 0x49, 0x83,
	0xec, 0x06, 0x96, 0xc6, 0x75, 0x3e, 0x30, 0x12, 0xfd, 0xc8, 0x9f, 0x60, 0x55, 0x1c, 0x5d, 0xa5,
	0x51, 0x10, 0xd9, 0xb1, 0xdd, 0x1d, 0xc4, 0xd2, 0x75, 0x35, 0x86, 0x6f, 0x5c, 0x89, 0xe1, 0xc6,
	0x5f, 0x7f, 0x93, 0x83, 0xe7, 0x16, 0xd2, 0xf0, 0x5c, 0x6a, 0x22, 0x3b, 0x78, 0x43, 0x80, 0x7a,
	0x5e, 0x5e, 0xc2, 0xea, 0x7d, 0x5a, 0x48, 0x81, 0xfa, 0xf4, 0xdd, 0x20, 0xfb, 0x00, 0x98, 0xad,
	0xd8, 0xe6, 0xec, 0x1f, 0x7f, 0xea, 0xdc, 0x5f, 0x7a, 0xf5, 0xf9, 0xfc, 0xdf, 0xdb, 0xf5, 0x57,
	0x1c, 0x56, 0x5b, 0xc7, 0x7e, 0xad, 0xfb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x64, 0x22,
	0x4c, 0x02, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	// error handling
	// This rpc will through an exception if the sent number is negative
	// The error being sent is of type INVALID_ARGUMENT
	SquareRoot(ctx context.Context, in *SquareRootRequest, opts ...grpc.CallOption) (*SquareRootReponse, error)
}

type calculatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorServiceClient(cc grpc.ClientConnInterface) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) SquareRoot(ctx context.Context, in *SquareRootRequest, opts ...grpc.CallOption) (*SquareRootReponse, error) {
	out := new(SquareRootReponse)
	err := c.cc.Invoke(ctx, "/calulator.CalculatorService/SquareRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	// error handling
	// This rpc will through an exception if the sent number is negative
	// The error being sent is of type INVALID_ARGUMENT
	SquareRoot(context.Context, *SquareRootRequest) (*SquareRootReponse, error)
}

// UnimplementedCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (*UnimplementedCalculatorServiceServer) SquareRoot(ctx context.Context, req *SquareRootRequest) (*SquareRootReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SquareRoot not implemented")
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_SquareRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SquareRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).SquareRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calulator.CalculatorService/SquareRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).SquareRoot(ctx, req.(*SquareRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calulator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SquareRoot",
			Handler:    _CalculatorService_SquareRoot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calculator/calc_server/calcpb/calc.proto",
}
