// Code generated by protoc-gen-go. DO NOT EDIT.
// source: average/average_server/averagepb/average.proto

package averagepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Average struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Average) Reset()         { *m = Average{} }
func (m *Average) String() string { return proto.CompactTextString(m) }
func (*Average) ProtoMessage()    {}
func (*Average) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3d2ccb5404230a3, []int{0}
}

func (m *Average) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Average.Unmarshal(m, b)
}
func (m *Average) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Average.Marshal(b, m, deterministic)
}
func (m *Average) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Average.Merge(m, src)
}
func (m *Average) XXX_Size() int {
	return xxx_messageInfo_Average.Size(m)
}
func (m *Average) XXX_DiscardUnknown() {
	xxx_messageInfo_Average.DiscardUnknown(m)
}

var xxx_messageInfo_Average proto.InternalMessageInfo

func (m *Average) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type LongAverageRequest struct {
	Average              *Average `protobuf:"bytes,1,opt,name=average,proto3" json:"average,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongAverageRequest) Reset()         { *m = LongAverageRequest{} }
func (m *LongAverageRequest) String() string { return proto.CompactTextString(m) }
func (*LongAverageRequest) ProtoMessage()    {}
func (*LongAverageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3d2ccb5404230a3, []int{1}
}

func (m *LongAverageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongAverageRequest.Unmarshal(m, b)
}
func (m *LongAverageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongAverageRequest.Marshal(b, m, deterministic)
}
func (m *LongAverageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongAverageRequest.Merge(m, src)
}
func (m *LongAverageRequest) XXX_Size() int {
	return xxx_messageInfo_LongAverageRequest.Size(m)
}
func (m *LongAverageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LongAverageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LongAverageRequest proto.InternalMessageInfo

func (m *LongAverageRequest) GetAverage() *Average {
	if m != nil {
		return m.Average
	}
	return nil
}

type LongAverageResponse struct {
	Result               float64  `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongAverageResponse) Reset()         { *m = LongAverageResponse{} }
func (m *LongAverageResponse) String() string { return proto.CompactTextString(m) }
func (*LongAverageResponse) ProtoMessage()    {}
func (*LongAverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3d2ccb5404230a3, []int{2}
}

func (m *LongAverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongAverageResponse.Unmarshal(m, b)
}
func (m *LongAverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongAverageResponse.Marshal(b, m, deterministic)
}
func (m *LongAverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongAverageResponse.Merge(m, src)
}
func (m *LongAverageResponse) XXX_Size() int {
	return xxx_messageInfo_LongAverageResponse.Size(m)
}
func (m *LongAverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LongAverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LongAverageResponse proto.InternalMessageInfo

func (m *LongAverageResponse) GetResult() float64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Average)(nil), "average.Average")
	proto.RegisterType((*LongAverageRequest)(nil), "average.LongAverageRequest")
	proto.RegisterType((*LongAverageResponse)(nil), "average.LongAverageResponse")
}

func init() {
	proto.RegisterFile("average/average_server/averagepb/average.proto", fileDescriptor_c3d2ccb5404230a3)
}

var fileDescriptor_c3d2ccb5404230a3 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4b, 0x2c, 0x4b, 0x2d,
	0x4a, 0x4c, 0x4f, 0xd5, 0x87, 0xd2, 0xf1, 0xc5, 0xa9, 0x45, 0x65, 0xa9, 0x45, 0x30, 0x6e, 0x41,
	0x12, 0x8c, 0xa5, 0x57, 0x50, 0x94, 0x5f, 0x92, 0x2f, 0xc4, 0x0e, 0xe5, 0x2a, 0x29, 0x72, 0xb1,
	0x3b, 0x42, 0x98, 0x42, 0x62, 0x5c, 0x6c, 0x79, 0xa5, 0xb9, 0x49, 0xa9, 0x45, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0xac, 0x41, 0x50, 0x9e, 0x92, 0x03, 0x97, 0x90, 0x4f, 0x7e, 0x5e, 0x3a, 0x54, 0x59,
	0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x16, 0x17, 0xcc, 0x0c, 0xb0, 0x72, 0x6e, 0x23,
	0x01, 0x98, 0x1b, 0xf4, 0x60, 0x2a, 0xe1, 0x96, 0xe8, 0x72, 0x09, 0xa3, 0x98, 0x50, 0x5c, 0x90,
	0x9f, 0x57, 0x0c, 0xb6, 0xb0, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0x04, 0x6c, 0x02, 0x63, 0x10, 0x94,
	0x67, 0x14, 0xc7, 0xc5, 0x07, 0x55, 0x1a, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0xe4, 0xc3,
	0xc5, 0x8d, 0x64, 0x80, 0x90, 0x34, 0xdc, 0x2a, 0x4c, 0x87, 0x49, 0xc9, 0x60, 0x97, 0x84, 0xd8,
	0xa9, 0xc4, 0xa0, 0xc1, 0xe8, 0xc4, 0x1d, 0xc5, 0x09, 0x0f, 0x97, 0x24, 0x36, 0x70, 0x80, 0x18,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xca, 0x40, 0x3c, 0xa7, 0x42, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AverageServiceClient is the client API for AverageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AverageServiceClient interface {
	// Client Streaming
	LongAverage(ctx context.Context, opts ...grpc.CallOption) (AverageService_LongAverageClient, error)
}

type averageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAverageServiceClient(cc grpc.ClientConnInterface) AverageServiceClient {
	return &averageServiceClient{cc}
}

func (c *averageServiceClient) LongAverage(ctx context.Context, opts ...grpc.CallOption) (AverageService_LongAverageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AverageService_serviceDesc.Streams[0], "/average.AverageService/LongAverage", opts...)
	if err != nil {
		return nil, err
	}
	x := &averageServiceLongAverageClient{stream}
	return x, nil
}

type AverageService_LongAverageClient interface {
	Send(*LongAverageRequest) error
	CloseAndRecv() (*LongAverageResponse, error)
	grpc.ClientStream
}

type averageServiceLongAverageClient struct {
	grpc.ClientStream
}

func (x *averageServiceLongAverageClient) Send(m *LongAverageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *averageServiceLongAverageClient) CloseAndRecv() (*LongAverageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(LongAverageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AverageServiceServer is the server API for AverageService service.
type AverageServiceServer interface {
	// Client Streaming
	LongAverage(AverageService_LongAverageServer) error
}

// UnimplementedAverageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAverageServiceServer struct {
}

func (*UnimplementedAverageServiceServer) LongAverage(srv AverageService_LongAverageServer) error {
	return status.Errorf(codes.Unimplemented, "method LongAverage not implemented")
}

func RegisterAverageServiceServer(s *grpc.Server, srv AverageServiceServer) {
	s.RegisterService(&_AverageService_serviceDesc, srv)
}

func _AverageService_LongAverage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AverageServiceServer).LongAverage(&averageServiceLongAverageServer{stream})
}

type AverageService_LongAverageServer interface {
	SendAndClose(*LongAverageResponse) error
	Recv() (*LongAverageRequest, error)
	grpc.ServerStream
}

type averageServiceLongAverageServer struct {
	grpc.ServerStream
}

func (x *averageServiceLongAverageServer) SendAndClose(m *LongAverageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *averageServiceLongAverageServer) Recv() (*LongAverageRequest, error) {
	m := new(LongAverageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AverageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "average.AverageService",
	HandlerType: (*AverageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LongAverage",
			Handler:       _AverageService_LongAverage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "average/average_server/averagepb/average.proto",
}
