// Code generated by protoc-gen-go. DO NOT EDIT.
// source: maximum/maximum_server/maximumpb/maximum.proto

package maximumpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Maximum struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Maximum) Reset()         { *m = Maximum{} }
func (m *Maximum) String() string { return proto.CompactTextString(m) }
func (*Maximum) ProtoMessage()    {}
func (*Maximum) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3e96a5268db0628, []int{0}
}

func (m *Maximum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Maximum.Unmarshal(m, b)
}
func (m *Maximum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Maximum.Marshal(b, m, deterministic)
}
func (m *Maximum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Maximum.Merge(m, src)
}
func (m *Maximum) XXX_Size() int {
	return xxx_messageInfo_Maximum.Size(m)
}
func (m *Maximum) XXX_DiscardUnknown() {
	xxx_messageInfo_Maximum.DiscardUnknown(m)
}

var xxx_messageInfo_Maximum proto.InternalMessageInfo

func (m *Maximum) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type MaxEveryoneRequest struct {
	Maximum              *Maximum `protobuf:"bytes,1,opt,name=maximum,proto3" json:"maximum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxEveryoneRequest) Reset()         { *m = MaxEveryoneRequest{} }
func (m *MaxEveryoneRequest) String() string { return proto.CompactTextString(m) }
func (*MaxEveryoneRequest) ProtoMessage()    {}
func (*MaxEveryoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3e96a5268db0628, []int{1}
}

func (m *MaxEveryoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxEveryoneRequest.Unmarshal(m, b)
}
func (m *MaxEveryoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxEveryoneRequest.Marshal(b, m, deterministic)
}
func (m *MaxEveryoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxEveryoneRequest.Merge(m, src)
}
func (m *MaxEveryoneRequest) XXX_Size() int {
	return xxx_messageInfo_MaxEveryoneRequest.Size(m)
}
func (m *MaxEveryoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxEveryoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MaxEveryoneRequest proto.InternalMessageInfo

func (m *MaxEveryoneRequest) GetMaximum() *Maximum {
	if m != nil {
		return m.Maximum
	}
	return nil
}

type MaxEveryoneResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxEveryoneResponse) Reset()         { *m = MaxEveryoneResponse{} }
func (m *MaxEveryoneResponse) String() string { return proto.CompactTextString(m) }
func (*MaxEveryoneResponse) ProtoMessage()    {}
func (*MaxEveryoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3e96a5268db0628, []int{2}
}

func (m *MaxEveryoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxEveryoneResponse.Unmarshal(m, b)
}
func (m *MaxEveryoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxEveryoneResponse.Marshal(b, m, deterministic)
}
func (m *MaxEveryoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxEveryoneResponse.Merge(m, src)
}
func (m *MaxEveryoneResponse) XXX_Size() int {
	return xxx_messageInfo_MaxEveryoneResponse.Size(m)
}
func (m *MaxEveryoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxEveryoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MaxEveryoneResponse proto.InternalMessageInfo

func (m *MaxEveryoneResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Maximum)(nil), "maximum.Maximum")
	proto.RegisterType((*MaxEveryoneRequest)(nil), "maximum.MaxEveryoneRequest")
	proto.RegisterType((*MaxEveryoneResponse)(nil), "maximum.MaxEveryoneResponse")
}

func init() {
	proto.RegisterFile("maximum/maximum_server/maximumpb/maximum.proto", fileDescriptor_f3e96a5268db0628)
}

var fileDescriptor_f3e96a5268db0628 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xcb, 0x4d, 0xac, 0xc8,
	0xcc, 0x2d, 0xcd, 0xd5, 0x87, 0xd2, 0xf1, 0xc5, 0xa9, 0x45, 0x65, 0xa9, 0x45, 0x30, 0x6e, 0x41,
	0x12, 0x8c, 0xa5, 0x57, 0x50, 0x94, 0x5f, 0x92, 0x2f, 0xc4, 0x0e, 0xe5, 0x2a, 0x29, 0x72, 0xb1,
	0xfb, 0x42, 0x98, 0x42, 0x62, 0x5c, 0x6c, 0x79, 0xa5, 0xb9, 0x49, 0xa9, 0x45, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0xac, 0x41, 0x50, 0x9e, 0x92, 0x03, 0x97, 0x90, 0x6f, 0x62, 0x85, 0x6b, 0x59, 0x6a,
	0x51, 0x65, 0x7e, 0x5e, 0x6a, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x16, 0x17, 0xcc,
	0x0c, 0xb0, 0x72, 0x6e, 0x23, 0x01, 0x98, 0x1b, 0xf4, 0xa0, 0x06, 0x06, 0xc1, 0x2d, 0xd1, 0xe5,
	0x12, 0x46, 0x31, 0xa1, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x15, 0x64, 0x61, 0x51, 0x6a, 0x71, 0x69,
	0x4e, 0x09, 0xcc, 0x42, 0x08, 0xcf, 0x28, 0x86, 0x8b, 0xcb, 0x37, 0xb1, 0x22, 0x38, 0xb5, 0xa8,
	0x2c, 0x33, 0x39, 0x55, 0xc8, 0x8f, 0x8b, 0x1b, 0x49, 0xb3, 0x90, 0x34, 0xb2, 0x35, 0x68, 0x8e,
	0x92, 0x92, 0xc1, 0x2e, 0x09, 0xb1, 0x4f, 0x89, 0x41, 0x83, 0xd1, 0x80, 0xd1, 0x89, 0x3b, 0x8a,
	0x13, 0x1e, 0x2a, 0x49, 0x6c, 0xe0, 0xe0, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x77, 0x11,
	0x80, 0x77, 0x40, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MaxServiceClient is the client API for MaxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MaxServiceClient interface {
	// BiDi streamer for maximum
	MaxEveryone(ctx context.Context, opts ...grpc.CallOption) (MaxService_MaxEveryoneClient, error)
}

type maxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMaxServiceClient(cc grpc.ClientConnInterface) MaxServiceClient {
	return &maxServiceClient{cc}
}

func (c *maxServiceClient) MaxEveryone(ctx context.Context, opts ...grpc.CallOption) (MaxService_MaxEveryoneClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MaxService_serviceDesc.Streams[0], "/maximum.MaxService/MaxEveryone", opts...)
	if err != nil {
		return nil, err
	}
	x := &maxServiceMaxEveryoneClient{stream}
	return x, nil
}

type MaxService_MaxEveryoneClient interface {
	Send(*MaxEveryoneRequest) error
	Recv() (*MaxEveryoneResponse, error)
	grpc.ClientStream
}

type maxServiceMaxEveryoneClient struct {
	grpc.ClientStream
}

func (x *maxServiceMaxEveryoneClient) Send(m *MaxEveryoneRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *maxServiceMaxEveryoneClient) Recv() (*MaxEveryoneResponse, error) {
	m := new(MaxEveryoneResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MaxServiceServer is the server API for MaxService service.
type MaxServiceServer interface {
	// BiDi streamer for maximum
	MaxEveryone(MaxService_MaxEveryoneServer) error
}

// UnimplementedMaxServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMaxServiceServer struct {
}

func (*UnimplementedMaxServiceServer) MaxEveryone(srv MaxService_MaxEveryoneServer) error {
	return status.Errorf(codes.Unimplemented, "method MaxEveryone not implemented")
}

func RegisterMaxServiceServer(s *grpc.Server, srv MaxServiceServer) {
	s.RegisterService(&_MaxService_serviceDesc, srv)
}

func _MaxService_MaxEveryone_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MaxServiceServer).MaxEveryone(&maxServiceMaxEveryoneServer{stream})
}

type MaxService_MaxEveryoneServer interface {
	Send(*MaxEveryoneResponse) error
	Recv() (*MaxEveryoneRequest, error)
	grpc.ServerStream
}

type maxServiceMaxEveryoneServer struct {
	grpc.ServerStream
}

func (x *maxServiceMaxEveryoneServer) Send(m *MaxEveryoneResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *maxServiceMaxEveryoneServer) Recv() (*MaxEveryoneRequest, error) {
	m := new(MaxEveryoneRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MaxService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "maximum.MaxService",
	HandlerType: (*MaxServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MaxEveryone",
			Handler:       _MaxService_MaxEveryone_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "maximum/maximum_server/maximumpb/maximum.proto",
}
